name: comment_command

on:
  issue_comment:
    types: [created, edited]

jobs:
  command:
    runs-on: ubuntu-latest
    # This job only runs for issue comments
    name: Check for "/" command
    if: contains(github.event.comment.body, '/')
    steps:
      - run: |
          python bots/Response.py ${{github.event.comment.body}} ${{github.event.issue.number}}
    # run python script against command (have checks for each command, script will execute accordingly)
    # script will implement Quests.py and provide a user inteface
    # either use json file I/O or pass in relavent arguments such as comment, user, issue, number