name: comment_command

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  comment:
    # This job only runs for issue comments
    name: comment detection
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/test')
    steps:
      - run: |
          echo "/test command issued"

