on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: contains(github.event.comment.html_url, '/test')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo /test command issued on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}