name:

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  comment:
    # This job only runs for issue comments
    name: comment detection
    if: contains(github.event.comment.html_url, '/test')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo /test command issued