name: Update README from Issue Comment

on:
  issue_comment:
    types: [created]

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Command is Issued
        id: check_command
        if: startsWith(github.event.comment.body, '/update-readme')
        run: echo "::set-output name=command::update-readme"

      - name: Checkout Repository
        uses: actions/checkout@v2  # Check out the repository's code

      - name: Call Manage README Workflow
        if: steps.check_command.outputs.command == 'update-readme'
        uses: ./actions/readme_manager
        with:
          action: 'create'  # Assuming you want to create a new README file
          user: ${{ github.event.comment.user.login }}
          content:  ${{ github.event.comment.body }}
          replace_pattern: ''


      - name: Commit Changes
        if: steps.check_command.outputs.command == 'update-readme'
        run: |
          git config --global user.name 'README_BOT'
          git config --global user.email 'connor.nicolai.aiton@gmail.com'
          git add README.md
          git commit -m "Update README via GitHub Actions"
          git push