name:

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  comment:
    # This job only runs for issue comments
    name: comment detection
    runs-on: ubuntu-latest
      - run: echo "hello world"
      if: ${{ github.event.issue.pull_request && github.event.comment.body == '/build' }}
      steps:
        - run: |
            echo "/test command issued"
