name:

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  comment:
    # This job only runs for issue comments
    name: comment detection
    runs-on: ubuntu-latest
      - run: echo hello world
      if: contains(github.event.comment.html_url, '/test')
      steps:
        - run: |
            echo /test command issued