name: Update README from Issue Comment

on:
  issue_comment:
    types: [created]

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Command is Issued
        id: check_command
        if: startsWith(github.event.comment.body, '/update-readme')
        run: echo "::set-output name=command::update-readme"

      - name: Extract Content
        id: extract_content
        if: steps.check_command.outputs.command == 'update-readme'
        run: echo "${{ github.event.comment.body }}" | cut -d' ' -f2-
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}

      - name: Call Manage README Workflow
        if: steps.check_command.outputs.command == 'update-readme'
        uses: ./.github/workflows/readme_manager.yml
        with:
          action: 'create'  # Assuming you want to create a new README file
          content: |
            User: ${{ github.event.comment.user.login }}
            Content: ${{ steps.extract_content.outputs.comment_body }}