name: comment_command

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  comment:
    # This job only runs for issue comments
    name: comment detection
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/build' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "/test command issued"
