name: Pull Request Checker
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check_pull_requests:
    runs-on: ubuntu-latest
    steps:
    - name: Display directory
      run: |
        pwd
        ls -a

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install requests

    - name: Run pull request checker
      run: python main.py