name: Manage README

on:
  workflow_call:
    inputs:
      action:
        required: true
      content:
        required: false
      replace_pattern:
        required: false

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Manage README
        id: update_readme
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const readmePath = `${process.env.GITHUB_WORKSPACE}/README.md`;
            let readmeContent = fs.readFileSync(readmePath, 'utf8');
            
            // get argument inputs, pass into script
            const action = '${{ inputs.action }}';
            const content = '${{ inputs.content || "" }}';
            const replacePattern = '${{ inputs.replace_pattern || "" }}';
            
            // action based off requested action
            switch (action) {
              case 'create':
                readmeContent = content; // overwrite/create
                break;
              case 'append':
                readmeContent += '\n' + content; // add to end
                break;
              case 'update':
                // look for specific to replace 
                // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp
                readmeContent = readmeContent.replace(new RegExp(replacePattern, 'g'), content);
                break;
              case 'delete':
                // delete specific
                readmeContent = readmeContent.replace(new RegExp(content, 'g'), '');
                break;
              default:
                console.log('Invalid action!');
            }
            
            // write to file
            fs.writeFileSync(readmePath, readmeContent);

      - name: Commit Changes
        if: ${{ steps.update_readme.outputs.changed == 'true' }}
        run: |
          git config --global user.name 'caiton1'
          git config --global user.email 'connor.nicolai.aiton@gmail.com' 
          git add README.md
          git commit -m "Update README via GitHub Actions"
          git push